# Generated by Django 5.1 on 2024-08-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(default='0.0.0.0', max_length=45)),
                ('user_agent', models.CharField(default='', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('country_name', models.CharField(default='Unknown', max_length=100)),
                ('region_name', models.CharField(default='Unknown', max_length=100)),
                ('zip_code', models.CharField(default='00000', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
            ],
        ),
    ]
