# Generated by Django 5.1 on 2024-08-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashakya_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
