# Generated by Django 5.1 on 2024-08-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashakya_api', '0002_visitor_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='referer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
