# Generated by Django 5.1 on 2024-08-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashakya_api', '0003_visitor_referer'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='download',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
