# Generated by Django 5.1 on 2024-08-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashakya_api', '0004_visitor_download'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='download',
        ),
        migrations.AddField(
            model_name='visitor',
            name='isp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
